-- mysql insert
INSERT INTO levels (name) VALUES
  ('campaign'),
  ('openworld'),
  ('endday'),
  ('trading'),
  ('farming'),
  ('fishing'),
  ('mining'),
  ('crafting'),
  ('casino'),
  ('fire'),
  ('pool'),
  ('magic'),
  ('slayer'),
  ('dungeon'),
  ('rpg'),
  ('combat'),
  ('agility'),
  ('summoning'),
  ('charisma');


-- sailing
-- aero, space
-- player owned houses poh




-- current_campaign INT,
--   level_campaign INT,
--   xp_campaign INT,
--   current_openworld INT,
--   level_openworld INT,
--   xp_openworld INT,
--   current_endday INT,
--   level_endday INT,
--   xp_endday INT,
--   current_trading INT,
--   level_trading INT,
--   xp_trading INT,
--   current_farming INT,
--   level_farming INT,
--   xp_farming INT,
--   current_fishing INT,
--   level_fishing INT,
--   xp_fishing INT,
--   current_mining INT,
--   level_mining INT,
--   xp_mining INT,
--   current_crafting INT,
--   level_crafting INT,
--   xp_crafting INT,
--   current_casino INT,
--   level_casino INT,
--   xp_casino INT,
--   current_fire INT,
--   level_fire INT,
--   xp_fire INT,
--   current_pool INT,
--   level_pool INT,
--   xp_pool INT,
--   current_magic INT,
--   level_magic INT,
--  xp_magic INT,
--  current_slayer INT,
--  level_slayer INT,
--  xp_slayer INT,
--  current_dungeon INT,
--  level_dungeon INT,
--  xp_dungeon INT,
--  current_rpg INT,
--  level_rpg INT,
--  xp_rpg INT,
--  current_combat INT,
--  level_combat INT,
--  xp_combat INT,
--  current_agility INT,
--  level_agility INT,
--  xp_agility INT,
--  current_summoning INT,
--  level_summoning INT,
--  xp_summoning INT,
--  current_charisma INT,
--  level_charisma INT,
--  xp_charisma INT,

--  main_level INT,
--  total_level INT,
--  total_xp INT,
--  quest_points INT,
--  quest_level INT