-- item insert data
INSERT INTO item (
  name,
  description,
  price,
  category,
  created_at,
  updated_at
) VALUES
  ('Balance', 'In-game currency balance', 0.00, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('MTX Coins', 'Microtransaction coins', 0.99, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Ancient Money', 'Ancient money', 0.50, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Alien Credits', 'Alien money', 0.50, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Monopoly money', 'Monopoly money - credits', 0.50, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- ('USD', 'usd USA-server money', 0.50, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- ('PESO', 'peso SA-server money', 0.50, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- ('GBP', 'gbp UK-server money', 0.50, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- ('EUR', 'eur euro-server money', 0.50, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- missing: RUSSIA, CHINA, AFRICA, MIDDLEEAST, other monies.
-- ('???', 'sea Asia-server money', 0.50, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- missing: antartica money?
-- ('???', 'out outback-server money', 0.50, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Casino Chips', 'Chips used in the casino', 0.50, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Token Spins', 'Tokens for spinning wheels', 0.10, 'Currency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Lemons', 'Fresh lemons for crafting', 0.05, 'Lemons-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Limes', 'Fresh limes for crafting', 0.05, 'Limes-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Shiny Lemons', 'Rare shiny lemons', 1.00, 'Lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Shiny Limes', 'Rare shiny limes', 1.00, 'Limes-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sugar', 'Sweet sugar for crafting', 0.03, 'Sugars-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Salt', 'Generic Salt for various uses', 0.02, 'Salts-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),			
  ('Honey', 'Sweet honey', 0.20, 'Honey-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Water', 'Essential water for survival', 0.01, 'Water-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sodas', 'Refreshing sodas', 0.30, 'Sodas-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Milk', 'Nutritious milk', 0.25, 'Milk-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Alcohol', 'Various alcoholic beverages', 2.00, 'Alcohol-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Ice', 'Ice for cooling', 0.01, 'Ice-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Heating', 'Heating resources', 0.10, 'Heat-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cups', 'Cups for serving drinks', 0.05, 'Cups-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Tea', 'Relaxing tea leaves', 0.15, 'Tea-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Coffee', 'Energizing coffee beans', 0.20, 'Coffee-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- Cooling / Ice ::
  ('Natural Heat', 'Heat from natural resources', 0.00, 'Heat-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Warm Heat', '', 0.50, 'Heat-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Hot Heat', '', 0.50, 'Heat-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Boiling Heat', '', 0.50, 'Heat-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Roaring Heat', '', 0.50, 'Heat-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Constant Heat', '', 0.50, 'Heat-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Frozen Heat', '', 0.50, 'Heat-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Lava Heat', '', 0.50, 'Heat-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nuclear Heat', '', 0.50, 'Heat-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Alien Heat', '', 0.50, 'Heat-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Small Ice', 'Small ice bits.', 0.01, 'Ice-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('High-Quality Small Ice', 'H.Q. Small ice bits.', 0.01, 'Ice-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fridge Ice', 'Ice from the fridge.', 0.01, 'Ice-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Ice Block', 'Large block of ice.', 0.05, 'Ice-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Factory Ice', 'Factory made Ice.', 0.50, 'Ice-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
  ('Ice cubes', 'Ice cubes', 0.50, 'Ice-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nice Ice cubes', 'Nice Ice cubes', 0.50, 'Ice-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Long Ice Cube', '', 0.50, 'Ice-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
  ('Big Ice Cube', '', 0.50, 'Ice-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Mini Ice Spheres', '', 0.50, 'Ice-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Big Ice Spheres', '', 0.50, 'Ice-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('High-Quality Ice', 'H.Q. Ice', 0.50, 'Ice-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Alien Ice', 'Alien Ice', 0.50, 'Ice-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Burning Ice', 'Ice on fire.', 0.50, 'Ice-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Shaved Ice', 'Shaved Ice', 0.50, 'Shaved-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('High-Quality Shaved Ice', '', 0.50, 'Shaved-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Blended Ice', '', 0.50, 'Blended-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('High-Quality Blended Ice', '', 0.50, 'Blended-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Slushie Ice', '', 0.50, 'Slushie-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('High-Quality Slushie Ice', '', 0.50, 'Slushie-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Chilled Glass', '', 0.50, 'Chilled-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Frozen Chilled Glass', '', 0.50, 'Chilled-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Frozen Jelly', '', 0.50, 'Fronzen-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Frozen Citrus', '', 0.50, 'Frozen-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Frozen Fruit', '', 0.50, 'Frozen-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Frozen Herbs', '', 0.50, 'Frozen-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Frozen Tea', '', 0.50, 'Frozen-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Frozen Coffee', '', 0.50, 'frozen-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Metal Cubes', '', 0.50, 'Metal-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Metal Balls', '', 0.50, 'Metal-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Stone Cubes', '', 0.50, 'Stone-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('High-Quality Stones', '', 0.50, 'Stone-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- Liquids ::
  ('Mineral Water', '', 0.50, 'Water-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Spring Water', '', 0.50, 'Water-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Flavoured Water', '', 0.50, 'Water-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Ancient Water', '', 0.50, 'Water-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Alien Water', '', 0.50, 'Water-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Magical Water', '', 0.50, 'Water-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Smart Water', '', 0.50, 'Water-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Super Water', '', 0.50, 'Water-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('High-Quality Soda', '', 0.50, 'Soda-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Branded Soda', '', 0.50, 'Soda-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Tonic water', '', 0.50, 'Tonic-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Beer', '', 0.50, 'Alcohol-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('IPA Beer', '', 0.50, 'Beer-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Lager Beer', '', 0.50, 'Beer-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Red Wine', '', 0.50, 'Wine-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('White Wine', '', 0.50, 'Wine-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Wine spirit', '', 0.50, 'Wine-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Brown spirit', '', 0.50, 'Spirits-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('White spirit', '', 0.50, 'Spirits-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('High-Quality Milk', '', 0.50, 'Milk-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Low-Fat Milk', '', 0.50, 'Milk-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Reduced-Fat Milk', '', 0.50, 'Milk-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Full-Fat Milk', '', 0.50, 'Milk-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cream', '', 0.50, 'Cream-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Heavy Cream', '', 0.50, 'Cream-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Whipped Cream', '', 0.50, 'CReam-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Almond Milk', '', 0.50, 'Milk-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Oat Milk', '', 0.50, 'Milk-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Soy Milk', '', 0.50, 'Milk-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- Salts ::
  ('Sodium', 'Generic Sodium compound created.', 0.50, 'salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sea Salt', 'Salt from the sea.', 0.50, 'salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fine Salts', 'Fine Salts', 0.50, 'salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Pink Salt', 'Pink Salt', 0.50, 'salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Black Salt', 'Black Salt', 0.50, 'salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('High-Quality Salt', 'High-Quality Salt', 0.50, 'salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Pure Na-Cl', 'Pure Na-Cl', 0.50, 'salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- ('Flavouring', 'Flavouring', 0.50, 'flavouring-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- flavour flavours
-- ('Kool-aid', 'Kool-aid', 0.50, 'flavouring-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- kool aid flavours
  ('Benzaldehyde', 'Benzaldehyde', 0.50, 'Flavouring-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Citric Acid', 'Citric Acid', 0.50, 'Acid-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sodium Acetate', 'Sodium Acetate', 0.50, 'Ester-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Amyl Acetate', 'Amyl Acetate', 0.50, 'Ester-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Citral Acetate', 'Citral Acetate', 0.50, 'Ester-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Citrus Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Spicy Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sweet Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Herbal Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fruity Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sour Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Bubbly Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Smokey Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Spice Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Glow Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Mystery Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Golden Sun Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Forest Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cherry Blossom Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Ruby Red Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Ocean Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Moon Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Umami Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- ('Colouring', 'Colouring Salts', 0.50, 'flavouring-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- ('Colouring', 'Food Colouring', 0.50, 'flavouring-n', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Ancient Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Magical Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Mythical Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Alien Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Future Salts', '', 0.50, 'Salts-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- Sugars ::
  ('Sugar Water Syrup', 'Syrup made from sugar water.', 0.10, 'syrup-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Natural Fructose Syrup', 'Natural syrup', 0.15, 'syrup-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Grenadine', 'Grenadine syrup', 0.50, 'grenadine-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- grenadine flavours 
  ('Molasses', 'Thick molasses', 0.20, 'molasses-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- molasses flavours 
  ('Fructose', 'Fructose', 0.50, 'chemicals-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sucrose', 'Sucrose', 0.50, 'chemicals-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Aspartame', 'Aspartame', 0.50, 'chemicals-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Saccharin', 'Saccharin', 0.50, 'chemicals-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fructose Corn Syrup', 'Fructose Corn Syrup', 0.50, 'syrup-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sugar Water Syrup', 'Sugar Water Syrup', 0.50, 'syrup-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- sugar water flavour
  ('White Sugar', 'White Sugar', 0.50, 'sugar-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Raw Sugar', 'Raw Sugar', 0.50, 'sugar-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Rock Sugar', 'Rock Sugar', 0.50, 'sugar-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('White Sugar Cubes', 'White Sugar Cubes', 0.50, 'sugar-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Raw Sugar Cubes', 'Raw Sugar Cubes', 0.50, 'sugar-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Alien Sugar', 'Alien Sugar', 0.50, 'alien-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Ancient Sugar', 'Sugar from ancient times.', 0.01, 'Ancient-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Natural Honey', 'Natural Honey', 0.50, 'honey-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Raw Honey', 'Raw Honey', 0.50, 'honey-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Processed Honey', 'Processed Honey', 0.50, 'Honey-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Organic Honey', 'Organic Honey', 0.50, 'Honey-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Vegan Honey', 'Vegan Honey', 0.50, 'Honey-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Alien Honey', 'Alien Honey', 0.50, 'Alien-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Super Honey', 'Super Honey', 0.50, 'Honey-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Ancient Honey', 'Ancient Honey', 0.50, 'Ancient-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Caramel', 'Caramel', 0.50, 'Caramel-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Toffee', 'Toffee', 0.50, 'Toffee-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- Base / Lemons ::
  ('Fresh Lemons', 'Fresh Lemons', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nice Lemons', 'Nice Lemons', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('High-Quality Lemons', 'H.Q. Lemons', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Pink Lemons', 'Pink Lemons', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fresh Pink Lemons', 'Fresh Pink Lemons', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nice Pink Lemons', 'Nice Pink Lemons', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Blue Lemons', 'Blue Lemons', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fresh Blue Lemons', 'Blue Lemons', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nice Blue Lemons', 'Blue Lemons', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Alien Lemons', 'Alien Lemons', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fresh Limes', 'Fresh Limes', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nice Limes', 'Fresh Limes', 0.50, 'lemons-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Yuzu', 'Yuzu', 0.50, 'yuzu-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fresh Yuzu', 'Fresh Yuzu', 0.50, 'yuzu-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nice Yuzu', 'Nice Yuzu', 0.50, 'yuzu-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Oranges', 'Oranges', 0.50, 'oranges-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fresh Oranges', 'Fresh Lemons', 0.50, 'oranges-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nice Oranges', 'Fresh Lemons', 0.50, 'oranges-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Mandarins', 'Mandarin Oranges', 0.50, 'mandarins-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Clementine', 'Clementine Oranges', 0.50, 'clementine-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Tangerines', 'Tangarines Oranges', 0.50, 'tangerines-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Blood Oranges', 'Blood Oranges', 0.50, 'oranges-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Grapefruit', 'Grapefruit', 0.50, 'grapefruit-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Pomelo', 'Grapefruit', 0.50, 'grapefruit-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cherries', 'Cherries', 0.50, 'cherry-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cocktail Cherry', 'Cocktail Cherries, found in fancy drinks.', 0.50, 'cherry-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Peach', 'Peaches', 0.50, 'peach-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Apple', 'Apple', 0.50, 'apple-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Melon', 'Melon', 0.50, 'melon-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Coconut', 'Coconut', 0.50, 'coconut-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- OTHERS ::
  ('Tea Mix', 'Regular Tea Mix', 0.50, 'tea-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Red Tea', 'Red Tea', 0.50, 'tea-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Black Tea', 'Black Tea', 0.50, 'tea-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('White Tea', 'Black Tea', 0.50, 'tea-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Green Tea', 'Green Tea', 0.50, 'tea-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Medium Roast Coffee', 'Coffee', 0.50, 'coffee-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Dark Roast Coffee', 'Coffee', 0.50, 'coffee-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Instant Coffee', 'Coffee', 0.50, 'coffee-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Coffee Mix', 'Coffee', 0.50, 'coffee-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Decafe Coffee', 'Coffee', 0.50, 'coffee-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Ginger', 'Ginger', 0.50, 'specials-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fresh Ginger', 'Fresh Ginger', 0.50, 'specials-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nice Ginger', 'Nice Ginger', 0.50, 'specials-s', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Vanilla Extract', 'Vanilla Extract', 0.50, 'vanilla-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Vanilla Flavouring', 'Vanilla Extract', 0.50, 'vanilla-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Vanilla Beans', 'Vanilla Beans', 0.50, 'vanilla-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Roasted Oak', 'Roasted Oak', 0.50, 'woods-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cinnamon Powder', 'Roasted Oak', 0.50, 'woods-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cinnamon Extract', 'Roasted Oak', 0.50, 'woods-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cinnamon Stick', 'Roasted Oak', 0.50, 'woods-b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


